### ISSUE TITLE
Page Loads at Bio

### ISSUE THREAD

**Issue by ato1120** [ato1120/ato1120.github.io#7]
When loading the page for the first time on desktop and mobile, it loads with the Bio section at the top. Should be CV.

![Screen Shot 2022-02-23 at 6 03 22 PM](https://user-images.githubusercontent.com/1930207/155424278-e75ea0eb-1d59-452a-a6fa-8bcc24eae93d.png)

**Comment by hdurand22** [comment]
This has been fixed
